spring:
  profiles:
    active: local, dev, qa, prod, test
  main: 
    banner-mode: off
  devtools:
    livereload:
      enabled: false
  batch:
    job:
      name: importMitreTechniqueData
      # available job names: importMitreTechniqueData, etc  